### ISSUE TITLE
Total Volume to specific Token

### ISSUE THREAD

**Issue by Devel484** [alekcangp/SwitcheoSmartContractExplorer#2]
Use last price of pairs to convert the total Volume of all pairs to a specific token(drop down or only NEO) to see the total volume in one token.

**Comment by alekcangp** [comment]
For example, use pair SWTH/NEO, buy 1000 SWTH for 1 NEO:
NEO offer is 1, NEO want is 0;
SWTH offer is 0, SWTH want is 0.
Correct total trading volume is 1 NEO or 1000 SWTH.
If NEO and SWTH volumes are converted in NEO and sum, the total volume will be 2 NEO, it's not correct.
To see the total volume of all NEO(ETH) pairs in NEO(ETH), need to look at NEO(ETH) total volume in the table.
Thanks for feedback.
