### ISSUE TITLE
Volumeview table

### ISSUE THREAD

**Issue by Devel484** [alekcangp/SwitcheoSmartContractExplorer#3]
Make a table instead of a list of volumes, quite better to read

| Token        | Want           | Offer  | Total | Converted to NEO |
| ------------- |:-------------:| -----:|-----:|-----:|
| first     |  |  |
| second    |       |    |
| ... |       |     |
|  |       |     | | Total in NEO|

**Comment by alekcangp** [comment]
I did it. Thanks for feedback.
